baseURL = "https://guxi.me/"
languageCode = "en-us"
title = "Garbage Collected"
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 12 
googleAnalytics = "UA-10190882-5"
enableRobotsTXT = true

[params]
  commentoEnable = true
  description = "A collection of my ephemeral thoughts"
  twitter = "https://twitter.com/Reasno_g"
  github = "https://github.com/Reasno"
  recent_posts_number = 5
