baseURL = "https://guxi.me/"
languageCode = "en-us"
title = "Garbage Collected"
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 12 
googleAnalytics = "UA-10190882-5"
enableRobotsTXT = true
pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[related]
  threshold = 20
  includeNewer = true
  toLower = true
  [[related.indices]]
    name= "tags"
    weight= 100
  [[related.indices]]  
    name= "date"
    weight= 10

[params]
  commentoEnable = true
  description = "A collection of my ephemeral thoughts"
  twitter = "https://twitter.com/Reasno_g"
  github = "https://github.com/Reasno"
  recent_posts_number = 5
  custom_css = ["css/syntax.css"]
