baseURL = "https://reasno.github.io/"
languageCode = "en-us"
title = "Garbage Collected"
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 10 
[params]
  description = "A collection of my ephemeral thoughts"
  twitter = "https://twitter.com/Reasno_g"
  github = "https://github.com/Reasno"
